# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: "mysql:5.7"
    ports:
      - '3310:3306'
    environment:
       - MYSQL_USER=user
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=test
       - MYSQL_ROOT_PASSWORD=1234
  adminer:
    image: adminer
    restart: always
    ports:
       - '6080:8080'
    links:
       - db
  web:
    image: bitnami/nginx:latest
    ports:
       - "8080:8080"
    volumes:
       - ./:/code
       - ./docker/nginx/sites-enabled/core.local:/opt/bitnami/nginx/conf/vhosts/site.conf
    links:
       - php
  php:
    build: docker/php
    volumes:
       -  ~/.ssh:/root/.ssh
       - ./:/code
       - $SSH_AUTH_SOCK:/ssh-agent
    links:
       - db
volumes:
  my-datavolume: